// This file is automatically generated from nem_mosaics.h.mako
// DO NOT EDIT

#ifndef __NEM_MOSAICS_H__
#define __NEM_MOSAICS_H__

#include "messages-nem.pb.h"

#define NEM_MOSAIC_DEFINITIONS_COUNT (6)

extern const NEMMosaicDefinition NEM_MOSAIC_DEFINITIONS[NEM_MOSAIC_DEFINITIONS_COUNT];
extern const NEMMosaicDefinition *NEM_MOSAIC_DEFINITION_XEM;

#endif
