#define VERSION_MAJOR 1
#define VERSION_MINOR 10
#define VERSION_PATCH 3

#define FIX_VERSION_MAJOR 1
#define FIX_VERSION_MINOR 8
#define FIX_VERSION_PATCH 0

#define VIEW_VERSION_MAJOR 1
#define VIEW_VERSION_MINOR 2
#define VIEW_VERSION_PATCH 0
