#define VERSION_MAJOR 1
#define VERSION_MINOR 9
#define VERSION_PATCH 0

#define FIX_VERSION_MAJOR 1
#define FIX_VERSION_MINOR 8
#define FIX_VERSION_PATCH 0

#define VIEW_VERSION_MAJOR 1
#define VIEW_VERSION_MINOR 1
#define VIEW_VERSION_PATCH 0
