/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 */

#include "messages-lisk.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint64_t LiskTransactionCommon_amount_default = 0ull;


const pb_field_t LiskGetAddress_fields[3] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, LiskGetAddress, address_n, address_n, 0),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, LiskGetAddress, show_display, address_n, 0),
    PB_LAST_FIELD
};

const pb_field_t LiskAddress_fields[2] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, LiskAddress, address, address, 0),
    PB_LAST_FIELD
};

const pb_field_t LiskGetPublicKey_fields[3] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, LiskGetPublicKey, address_n, address_n, 0),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, LiskGetPublicKey, show_display, address_n, 0),
    PB_LAST_FIELD
};

const pb_field_t LiskPublicKey_fields[2] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, STATIC  , FIRST, LiskPublicKey, public_key, public_key, 0),
    PB_LAST_FIELD
};

const pb_field_t LiskSignTx_fields[3] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, LiskSignTx, address_n, address_n, 0),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, LiskSignTx, transaction, address_n, &LiskTransactionCommon_fields),
    PB_LAST_FIELD
};

const pb_field_t LiskTransactionCommon_fields[10] = {
    PB_FIELD(  1, UENUM   , OPTIONAL, STATIC  , FIRST, LiskTransactionCommon, type, type, 0),
    PB_FIELD(  2, UINT64  , OPTIONAL, STATIC  , OTHER, LiskTransactionCommon, amount, type, &LiskTransactionCommon_amount_default),
    PB_FIELD(  3, UINT64  , OPTIONAL, STATIC  , OTHER, LiskTransactionCommon, fee, amount, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, STATIC  , OTHER, LiskTransactionCommon, recipient_id, fee, 0),
    PB_FIELD(  5, BYTES   , OPTIONAL, STATIC  , OTHER, LiskTransactionCommon, sender_public_key, recipient_id, 0),
    PB_FIELD(  6, BYTES   , OPTIONAL, STATIC  , OTHER, LiskTransactionCommon, requester_public_key, sender_public_key, 0),
    PB_FIELD(  7, BYTES   , OPTIONAL, STATIC  , OTHER, LiskTransactionCommon, signature, requester_public_key, 0),
    PB_FIELD(  8, UINT32  , OPTIONAL, STATIC  , OTHER, LiskTransactionCommon, timestamp, signature, 0),
    PB_FIELD(  9, MESSAGE , OPTIONAL, STATIC  , OTHER, LiskTransactionCommon, asset, timestamp, &LiskTransactionAsset_fields),
    PB_LAST_FIELD
};

const pb_field_t LiskTransactionAsset_fields[6] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, LiskTransactionAsset, signature, signature, &LiskSignatureType_fields),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, LiskTransactionAsset, delegate, signature, &LiskDelegateType_fields),
    PB_FIELD(  3, STRING  , REPEATED, STATIC  , OTHER, LiskTransactionAsset, votes, delegate, 0),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, LiskTransactionAsset, multisignature, votes, &LiskMultisignatureType_fields),
    PB_FIELD(  5, STRING  , OPTIONAL, STATIC  , OTHER, LiskTransactionAsset, data, multisignature, 0),
    PB_LAST_FIELD
};

const pb_field_t LiskSignatureType_fields[2] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, STATIC  , FIRST, LiskSignatureType, public_key, public_key, 0),
    PB_LAST_FIELD
};

const pb_field_t LiskDelegateType_fields[2] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, LiskDelegateType, username, username, 0),
    PB_LAST_FIELD
};

const pb_field_t LiskMultisignatureType_fields[4] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, LiskMultisignatureType, min, min, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, LiskMultisignatureType, life_time, min, 0),
    PB_FIELD(  3, STRING  , REPEATED, STATIC  , OTHER, LiskMultisignatureType, keys_group, life_time, 0),
    PB_LAST_FIELD
};

const pb_field_t LiskSignedTx_fields[2] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, STATIC  , FIRST, LiskSignedTx, signature, signature, 0),
    PB_LAST_FIELD
};

const pb_field_t LiskSignMessage_fields[3] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, LiskSignMessage, address_n, address_n, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, STATIC  , OTHER, LiskSignMessage, message, address_n, 0),
    PB_LAST_FIELD
};

const pb_field_t LiskMessageSignature_fields[3] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, STATIC  , FIRST, LiskMessageSignature, public_key, public_key, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, STATIC  , OTHER, LiskMessageSignature, signature, public_key, 0),
    PB_LAST_FIELD
};

const pb_field_t LiskVerifyMessage_fields[4] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, STATIC  , FIRST, LiskVerifyMessage, public_key, public_key, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, STATIC  , OTHER, LiskVerifyMessage, signature, public_key, 0),
    PB_FIELD(  3, BYTES   , OPTIONAL, STATIC  , OTHER, LiskVerifyMessage, message, signature, 0),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(LiskSignTx, transaction) < 65536 && pb_membersize(LiskTransactionCommon, asset) < 65536 && pb_membersize(LiskTransactionAsset, signature) < 65536 && pb_membersize(LiskTransactionAsset, delegate) < 65536 && pb_membersize(LiskTransactionAsset, multisignature) < 65536 && pb_membersize(LiskSignMessage, message) < 65536 && pb_membersize(LiskVerifyMessage, message) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_LiskGetAddress_LiskAddress_LiskGetPublicKey_LiskPublicKey_LiskSignTx_LiskTransactionCommon_LiskTransactionAsset_LiskSignatureType_LiskDelegateType_LiskMultisignatureType_LiskSignedTx_LiskSignMessage_LiskMessageSignature_LiskVerifyMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for LiskVerifyMessage.message is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
