/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 */

#ifndef PB_HW_TREZOR_MESSAGES_BITCOIN_MESSAGES_BITCOIN_PB_H_INCLUDED
#define PB_HW_TREZOR_MESSAGES_BITCOIN_MESSAGES_BITCOIN_PB_H_INCLUDED
#include "pb.h"
#include "messages-common.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _InputScriptType {
    InputScriptType_SPENDADDRESS = 0,
    InputScriptType_SPENDMULTISIG = 1,
    InputScriptType_EXTERNAL = 2,
    InputScriptType_SPENDWITNESS = 3,
    InputScriptType_SPENDP2SHWITNESS = 4
} InputScriptType;
#define _InputScriptType_MIN InputScriptType_SPENDADDRESS
#define _InputScriptType_MAX InputScriptType_SPENDP2SHWITNESS
#define _InputScriptType_ARRAYSIZE ((InputScriptType)(InputScriptType_SPENDP2SHWITNESS+1))

typedef enum _RequestType {
    RequestType_TXINPUT = 0,
    RequestType_TXOUTPUT = 1,
    RequestType_TXMETA = 2,
    RequestType_TXFINISHED = 3,
    RequestType_TXEXTRADATA = 4
} RequestType;
#define _RequestType_MIN RequestType_TXINPUT
#define _RequestType_MAX RequestType_TXEXTRADATA
#define _RequestType_ARRAYSIZE ((RequestType)(RequestType_TXEXTRADATA+1))

typedef enum _OutputScriptType {
    OutputScriptType_PAYTOADDRESS = 0,
    OutputScriptType_PAYTOSCRIPTHASH = 1,
    OutputScriptType_PAYTOMULTISIG = 2,
    OutputScriptType_PAYTOOPRETURN = 3,
    OutputScriptType_PAYTOWITNESS = 4,
    OutputScriptType_PAYTOP2SHWITNESS = 5
} OutputScriptType;
#define _OutputScriptType_MIN OutputScriptType_PAYTOADDRESS
#define _OutputScriptType_MAX OutputScriptType_PAYTOP2SHWITNESS
#define _OutputScriptType_ARRAYSIZE ((OutputScriptType)(OutputScriptType_PAYTOP2SHWITNESS+1))

/* Struct definitions */
typedef struct _Address {
    char address[130];
/* @@protoc_insertion_point(struct:Address) */
} Address;

typedef struct _GetPublicKey {
    pb_size_t address_n_count;
    uint32_t address_n[8];
    bool has_ecdsa_curve_name;
    char ecdsa_curve_name[32];
    bool has_show_display;
    bool show_display;
    bool has_coin_name;
    char coin_name[21];
    bool has_script_type;
    InputScriptType script_type;
/* @@protoc_insertion_point(struct:GetPublicKey) */
} GetPublicKey;

typedef struct _HDNodePathType {
    HDNodeType node;
    pb_size_t address_n_count;
    uint32_t address_n[8];
/* @@protoc_insertion_point(struct:HDNodePathType) */
} HDNodePathType;

typedef PB_BYTES_ARRAY_T(65) MessageSignature_signature_t;
typedef struct _MessageSignature {
    bool has_address;
    char address[130];
    bool has_signature;
    MessageSignature_signature_t signature;
/* @@protoc_insertion_point(struct:MessageSignature) */
} MessageSignature;

typedef struct _PublicKey {
    bool has_node;
    HDNodeType node;
    bool has_xpub;
    char xpub[113];
/* @@protoc_insertion_point(struct:PublicKey) */
} PublicKey;

typedef PB_BYTES_ARRAY_T(1024) SignMessage_message_t;
typedef struct _SignMessage {
    pb_size_t address_n_count;
    uint32_t address_n[8];
    SignMessage_message_t message;
    bool has_coin_name;
    char coin_name[21];
    bool has_script_type;
    InputScriptType script_type;
/* @@protoc_insertion_point(struct:SignMessage) */
} SignMessage;

typedef struct _SignTx {
    uint32_t outputs_count;
    uint32_t inputs_count;
    bool has_coin_name;
    char coin_name[21];
    bool has_version;
    uint32_t version;
    bool has_lock_time;
    uint32_t lock_time;
    bool has_expiry;
    uint32_t expiry;
    bool has_overwintered;
    bool overwintered;
    bool has_version_group_id;
    uint32_t version_group_id;
    bool has_timestamp;
    uint32_t timestamp;
    bool has_branch_id;
    uint32_t branch_id;
/* @@protoc_insertion_point(struct:SignTx) */
} SignTx;

typedef PB_BYTES_ARRAY_T(520) TxOutputBinType_script_pubkey_t;
typedef struct _TxOutputBinType {
    uint64_t amount;
    TxOutputBinType_script_pubkey_t script_pubkey;
    bool has_decred_script_version;
    uint32_t decred_script_version;
/* @@protoc_insertion_point(struct:TxOutputBinType) */
} TxOutputBinType;

typedef PB_BYTES_ARRAY_T(32) TxRequestDetailsType_tx_hash_t;
typedef struct _TxRequestDetailsType {
    bool has_request_index;
    uint32_t request_index;
    bool has_tx_hash;
    TxRequestDetailsType_tx_hash_t tx_hash;
    bool has_extra_data_len;
    uint32_t extra_data_len;
    bool has_extra_data_offset;
    uint32_t extra_data_offset;
/* @@protoc_insertion_point(struct:TxRequestDetailsType) */
} TxRequestDetailsType;

typedef PB_BYTES_ARRAY_T(73) TxRequestSerializedType_signature_t;
typedef PB_BYTES_ARRAY_T(2048) TxRequestSerializedType_serialized_tx_t;
typedef struct _TxRequestSerializedType {
    bool has_signature_index;
    uint32_t signature_index;
    bool has_signature;
    TxRequestSerializedType_signature_t signature;
    bool has_serialized_tx;
    TxRequestSerializedType_serialized_tx_t serialized_tx;
/* @@protoc_insertion_point(struct:TxRequestSerializedType) */
} TxRequestSerializedType;

typedef PB_BYTES_ARRAY_T(65) VerifyMessage_signature_t;
typedef PB_BYTES_ARRAY_T(1024) VerifyMessage_message_t;
typedef struct _VerifyMessage {
    bool has_address;
    char address[130];
    bool has_signature;
    VerifyMessage_signature_t signature;
    bool has_message;
    VerifyMessage_message_t message;
    bool has_coin_name;
    char coin_name[21];
/* @@protoc_insertion_point(struct:VerifyMessage) */
} VerifyMessage;

typedef PB_BYTES_ARRAY_T(73) MultisigRedeemScriptType_signatures_t;
typedef struct _MultisigRedeemScriptType {
    pb_size_t pubkeys_count;
    HDNodePathType pubkeys[15];
    pb_size_t signatures_count;
    MultisigRedeemScriptType_signatures_t signatures[15];
    bool has_m;
    uint32_t m;
    pb_size_t nodes_count;
    HDNodeType nodes[15];
    pb_size_t address_n_count;
    uint32_t address_n[8];
/* @@protoc_insertion_point(struct:MultisigRedeemScriptType) */
} MultisigRedeemScriptType;

typedef struct _TxRequest {
    bool has_request_type;
    RequestType request_type;
    bool has_details;
    TxRequestDetailsType details;
    bool has_serialized;
    TxRequestSerializedType serialized;
/* @@protoc_insertion_point(struct:TxRequest) */
} TxRequest;

typedef struct _GetAddress {
    pb_size_t address_n_count;
    uint32_t address_n[8];
    bool has_coin_name;
    char coin_name[21];
    bool has_show_display;
    bool show_display;
    bool has_multisig;
    MultisigRedeemScriptType multisig;
    bool has_script_type;
    InputScriptType script_type;
/* @@protoc_insertion_point(struct:GetAddress) */
} GetAddress;

typedef PB_BYTES_ARRAY_T(32) TxInputType_prev_hash_t;
typedef PB_BYTES_ARRAY_T(1650) TxInputType_script_sig_t;
typedef PB_BYTES_ARRAY_T(32) TxInputType_prev_block_hash_bip115_t;
typedef struct _TxInputType {
    pb_size_t address_n_count;
    uint32_t address_n[8];
    TxInputType_prev_hash_t prev_hash;
    uint32_t prev_index;
    bool has_script_sig;
    TxInputType_script_sig_t script_sig;
    bool has_sequence;
    uint32_t sequence;
    bool has_script_type;
    InputScriptType script_type;
    bool has_multisig;
    MultisigRedeemScriptType multisig;
    bool has_amount;
    uint64_t amount;
    bool has_decred_tree;
    uint32_t decred_tree;
    bool has_decred_script_version;
    uint32_t decred_script_version;
    bool has_prev_block_hash_bip115;
    TxInputType_prev_block_hash_bip115_t prev_block_hash_bip115;
    bool has_prev_block_height_bip115;
    uint32_t prev_block_height_bip115;
/* @@protoc_insertion_point(struct:TxInputType) */
} TxInputType;

typedef PB_BYTES_ARRAY_T(80) TxOutputType_op_return_data_t;
typedef PB_BYTES_ARRAY_T(32) TxOutputType_block_hash_bip115_t;
typedef struct _TxOutputType {
    bool has_address;
    char address[130];
    pb_size_t address_n_count;
    uint32_t address_n[8];
    uint64_t amount;
    OutputScriptType script_type;
    bool has_multisig;
    MultisigRedeemScriptType multisig;
    bool has_op_return_data;
    TxOutputType_op_return_data_t op_return_data;
    bool has_decred_script_version;
    uint32_t decred_script_version;
    bool has_block_hash_bip115;
    TxOutputType_block_hash_bip115_t block_hash_bip115;
    bool has_block_height_bip115;
    uint32_t block_height_bip115;
/* @@protoc_insertion_point(struct:TxOutputType) */
} TxOutputType;

typedef PB_BYTES_ARRAY_T(1024) TransactionType_extra_data_t;
typedef struct _TransactionType {
    bool has_version;
    uint32_t version;
    pb_size_t inputs_count;
    TxInputType inputs[1];
    pb_size_t bin_outputs_count;
    TxOutputBinType bin_outputs[1];
    bool has_lock_time;
    uint32_t lock_time;
    pb_size_t outputs_count;
    TxOutputType outputs[1];
    bool has_inputs_cnt;
    uint32_t inputs_cnt;
    bool has_outputs_cnt;
    uint32_t outputs_cnt;
    bool has_extra_data;
    TransactionType_extra_data_t extra_data;
    bool has_extra_data_len;
    uint32_t extra_data_len;
    bool has_expiry;
    uint32_t expiry;
    bool has_overwintered;
    bool overwintered;
    bool has_version_group_id;
    uint32_t version_group_id;
    bool has_timestamp;
    uint32_t timestamp;
    bool has_branch_id;
    uint32_t branch_id;
/* @@protoc_insertion_point(struct:TransactionType) */
} TransactionType;

typedef struct _TxAck {
    bool has_tx;
    TransactionType tx;
/* @@protoc_insertion_point(struct:TxAck) */
} TxAck;

/* Default values for struct fields */
extern const char GetPublicKey_coin_name_default[21];
extern const InputScriptType GetPublicKey_script_type_default;
extern const char GetAddress_coin_name_default[21];
extern const InputScriptType GetAddress_script_type_default;
extern const char SignMessage_coin_name_default[21];
extern const InputScriptType SignMessage_script_type_default;
extern const char VerifyMessage_coin_name_default[21];
extern const char SignTx_coin_name_default[21];
extern const uint32_t SignTx_version_default;
extern const uint32_t SignTx_lock_time_default;
extern const uint32_t TxInputType_sequence_default;
extern const InputScriptType TxInputType_script_type_default;

/* Initializer values for message structs */
#define MultisigRedeemScriptType_init_default    {0, {HDNodePathType_init_default, HDNodePathType_init_default, HDNodePathType_init_default, HDNodePathType_init_default, HDNodePathType_init_default, HDNodePathType_init_default, HDNodePathType_init_default, HDNodePathType_init_default, HDNodePathType_init_default, HDNodePathType_init_default, HDNodePathType_init_default, HDNodePathType_init_default, HDNodePathType_init_default, HDNodePathType_init_default, HDNodePathType_init_default}, 0, {{0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}}, false, 0, 0, {HDNodeType_init_default, HDNodeType_init_default, HDNodeType_init_default, HDNodeType_init_default, HDNodeType_init_default, HDNodeType_init_default, HDNodeType_init_default, HDNodeType_init_default, HDNodeType_init_default, HDNodeType_init_default, HDNodeType_init_default, HDNodeType_init_default, HDNodeType_init_default, HDNodeType_init_default, HDNodeType_init_default}, 0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define HDNodePathType_init_default              {HDNodeType_init_default, 0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define GetPublicKey_init_default                {0, {0, 0, 0, 0, 0, 0, 0, 0}, false, "", false, 0, false, "Bitcoin", false, InputScriptType_SPENDADDRESS}
#define PublicKey_init_default                   {false, HDNodeType_init_default, false, ""}
#define GetAddress_init_default                  {0, {0, 0, 0, 0, 0, 0, 0, 0}, false, "Bitcoin", false, 0, false, MultisigRedeemScriptType_init_default, false, InputScriptType_SPENDADDRESS}
#define Address_init_default                     {""}
#define SignMessage_init_default                 {0, {0, 0, 0, 0, 0, 0, 0, 0}, {0, {0}}, false, "Bitcoin", false, InputScriptType_SPENDADDRESS}
#define MessageSignature_init_default            {false, "", false, {0, {0}}}
#define VerifyMessage_init_default               {false, "", false, {0, {0}}, false, {0, {0}}, false, "Bitcoin"}
#define SignTx_init_default                      {0, 0, false, "Bitcoin", false, 1u, false, 0u, false, 0, false, 0, false, 0, false, 0, false, 0}
#define TxRequest_init_default                   {false, _RequestType_MIN, false, TxRequestDetailsType_init_default, false, TxRequestSerializedType_init_default}
#define TxRequestDetailsType_init_default        {false, 0, false, {0, {0}}, false, 0, false, 0}
#define TxRequestSerializedType_init_default     {false, 0, false, {0, {0}}, false, {0, {0}}}
#define TxAck_init_default                       {false, TransactionType_init_default}
#define TransactionType_init_default             {false, 0, 0, {TxInputType_init_default}, 0, {TxOutputBinType_init_default}, false, 0, 0, {TxOutputType_init_default}, false, 0, false, 0, false, {0, {0}}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define TxInputType_init_default                 {0, {0, 0, 0, 0, 0, 0, 0, 0}, {0, {0}}, 0, false, {0, {0}}, false, 4294967295u, false, InputScriptType_SPENDADDRESS, false, MultisigRedeemScriptType_init_default, false, 0, false, 0, false, 0, false, {0, {0}}, false, 0}
#define TxOutputBinType_init_default             {0, {0, {0}}, false, 0}
#define TxOutputType_init_default                {false, "", 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, _OutputScriptType_MIN, false, MultisigRedeemScriptType_init_default, false, {0, {0}}, false, 0, false, {0, {0}}, false, 0}
#define MultisigRedeemScriptType_init_zero       {0, {HDNodePathType_init_zero, HDNodePathType_init_zero, HDNodePathType_init_zero, HDNodePathType_init_zero, HDNodePathType_init_zero, HDNodePathType_init_zero, HDNodePathType_init_zero, HDNodePathType_init_zero, HDNodePathType_init_zero, HDNodePathType_init_zero, HDNodePathType_init_zero, HDNodePathType_init_zero, HDNodePathType_init_zero, HDNodePathType_init_zero, HDNodePathType_init_zero}, 0, {{0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}}, false, 0, 0, {HDNodeType_init_zero, HDNodeType_init_zero, HDNodeType_init_zero, HDNodeType_init_zero, HDNodeType_init_zero, HDNodeType_init_zero, HDNodeType_init_zero, HDNodeType_init_zero, HDNodeType_init_zero, HDNodeType_init_zero, HDNodeType_init_zero, HDNodeType_init_zero, HDNodeType_init_zero, HDNodeType_init_zero, HDNodeType_init_zero}, 0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define HDNodePathType_init_zero                 {HDNodeType_init_zero, 0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define GetPublicKey_init_zero                   {0, {0, 0, 0, 0, 0, 0, 0, 0}, false, "", false, 0, false, "", false, _InputScriptType_MIN}
#define PublicKey_init_zero                      {false, HDNodeType_init_zero, false, ""}
#define GetAddress_init_zero                     {0, {0, 0, 0, 0, 0, 0, 0, 0}, false, "", false, 0, false, MultisigRedeemScriptType_init_zero, false, _InputScriptType_MIN}
#define Address_init_zero                        {""}
#define SignMessage_init_zero                    {0, {0, 0, 0, 0, 0, 0, 0, 0}, {0, {0}}, false, "", false, _InputScriptType_MIN}
#define MessageSignature_init_zero               {false, "", false, {0, {0}}}
#define VerifyMessage_init_zero                  {false, "", false, {0, {0}}, false, {0, {0}}, false, ""}
#define SignTx_init_zero                         {0, 0, false, "", false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define TxRequest_init_zero                      {false, _RequestType_MIN, false, TxRequestDetailsType_init_zero, false, TxRequestSerializedType_init_zero}
#define TxRequestDetailsType_init_zero           {false, 0, false, {0, {0}}, false, 0, false, 0}
#define TxRequestSerializedType_init_zero        {false, 0, false, {0, {0}}, false, {0, {0}}}
#define TxAck_init_zero                          {false, TransactionType_init_zero}
#define TransactionType_init_zero                {false, 0, 0, {TxInputType_init_zero}, 0, {TxOutputBinType_init_zero}, false, 0, 0, {TxOutputType_init_zero}, false, 0, false, 0, false, {0, {0}}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define TxInputType_init_zero                    {0, {0, 0, 0, 0, 0, 0, 0, 0}, {0, {0}}, 0, false, {0, {0}}, false, 0, false, _InputScriptType_MIN, false, MultisigRedeemScriptType_init_zero, false, 0, false, 0, false, 0, false, {0, {0}}, false, 0}
#define TxOutputBinType_init_zero                {0, {0, {0}}, false, 0}
#define TxOutputType_init_zero                   {false, "", 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, _OutputScriptType_MIN, false, MultisigRedeemScriptType_init_zero, false, {0, {0}}, false, 0, false, {0, {0}}, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Address_address_tag                      1
#define GetPublicKey_address_n_tag               1
#define GetPublicKey_ecdsa_curve_name_tag        2
#define GetPublicKey_show_display_tag            3
#define GetPublicKey_coin_name_tag               4
#define GetPublicKey_script_type_tag             5
#define HDNodePathType_node_tag                  1
#define HDNodePathType_address_n_tag             2
#define MessageSignature_address_tag             1
#define MessageSignature_signature_tag           2
#define PublicKey_node_tag                       1
#define PublicKey_xpub_tag                       2
#define SignMessage_address_n_tag                1
#define SignMessage_message_tag                  2
#define SignMessage_coin_name_tag                3
#define SignMessage_script_type_tag              4
#define SignTx_outputs_count_tag                 1
#define SignTx_inputs_count_tag                  2
#define SignTx_coin_name_tag                     3
#define SignTx_version_tag                       4
#define SignTx_lock_time_tag                     5
#define SignTx_expiry_tag                        6
#define SignTx_overwintered_tag                  7
#define SignTx_version_group_id_tag              8
#define SignTx_timestamp_tag                     9
#define SignTx_branch_id_tag                     10
#define TxOutputBinType_amount_tag               1
#define TxOutputBinType_script_pubkey_tag        2
#define TxOutputBinType_decred_script_version_tag 3
#define TxRequestDetailsType_request_index_tag   1
#define TxRequestDetailsType_tx_hash_tag         2
#define TxRequestDetailsType_extra_data_len_tag  3
#define TxRequestDetailsType_extra_data_offset_tag 4
#define TxRequestSerializedType_signature_index_tag 1
#define TxRequestSerializedType_signature_tag    2
#define TxRequestSerializedType_serialized_tx_tag 3
#define VerifyMessage_address_tag                1
#define VerifyMessage_signature_tag              2
#define VerifyMessage_message_tag                3
#define VerifyMessage_coin_name_tag              4
#define MultisigRedeemScriptType_pubkeys_tag     1
#define MultisigRedeemScriptType_signatures_tag  2
#define MultisigRedeemScriptType_m_tag           3
#define MultisigRedeemScriptType_nodes_tag       4
#define MultisigRedeemScriptType_address_n_tag   5
#define TxRequest_request_type_tag               1
#define TxRequest_details_tag                    2
#define TxRequest_serialized_tag                 3
#define GetAddress_address_n_tag                 1
#define GetAddress_coin_name_tag                 2
#define GetAddress_show_display_tag              3
#define GetAddress_multisig_tag                  4
#define GetAddress_script_type_tag               5
#define TxInputType_address_n_tag                1
#define TxInputType_prev_hash_tag                2
#define TxInputType_prev_index_tag               3
#define TxInputType_script_sig_tag               4
#define TxInputType_sequence_tag                 5
#define TxInputType_script_type_tag              6
#define TxInputType_multisig_tag                 7
#define TxInputType_amount_tag                   8
#define TxInputType_decred_tree_tag              9
#define TxInputType_decred_script_version_tag    10
#define TxInputType_prev_block_hash_bip115_tag   11
#define TxInputType_prev_block_height_bip115_tag 12
#define TxOutputType_address_tag                 1
#define TxOutputType_address_n_tag               2
#define TxOutputType_amount_tag                  3
#define TxOutputType_script_type_tag             4
#define TxOutputType_multisig_tag                5
#define TxOutputType_op_return_data_tag          6
#define TxOutputType_decred_script_version_tag   7
#define TxOutputType_block_hash_bip115_tag       8
#define TxOutputType_block_height_bip115_tag     9
#define TransactionType_version_tag              1
#define TransactionType_inputs_tag               2
#define TransactionType_bin_outputs_tag          3
#define TransactionType_lock_time_tag            4
#define TransactionType_outputs_tag              5
#define TransactionType_inputs_cnt_tag           6
#define TransactionType_outputs_cnt_tag          7
#define TransactionType_extra_data_tag           8
#define TransactionType_extra_data_len_tag       9
#define TransactionType_expiry_tag               10
#define TransactionType_overwintered_tag         11
#define TransactionType_version_group_id_tag     12
#define TransactionType_timestamp_tag            13
#define TransactionType_branch_id_tag            14
#define TxAck_tx_tag                             1

/* Struct field encoding specification for nanopb */
extern const pb_field_t MultisigRedeemScriptType_fields[6];
extern const pb_field_t HDNodePathType_fields[3];
extern const pb_field_t GetPublicKey_fields[6];
extern const pb_field_t PublicKey_fields[3];
extern const pb_field_t GetAddress_fields[6];
extern const pb_field_t Address_fields[2];
extern const pb_field_t SignMessage_fields[5];
extern const pb_field_t MessageSignature_fields[3];
extern const pb_field_t VerifyMessage_fields[5];
extern const pb_field_t SignTx_fields[11];
extern const pb_field_t TxRequest_fields[4];
extern const pb_field_t TxRequestDetailsType_fields[5];
extern const pb_field_t TxRequestSerializedType_fields[4];
extern const pb_field_t TxAck_fields[2];
extern const pb_field_t TransactionType_fields[15];
extern const pb_field_t TxInputType_fields[13];
extern const pb_field_t TxOutputBinType_fields[4];
extern const pb_field_t TxOutputType_fields[10];

/* Maximum encoded size of messages (where known) */
#define MultisigRedeemScriptType_size            (2169 + 15*HDNodeType_size + 15*HDNodeType_size)
#define HDNodePathType_size                      (54 + HDNodeType_size)
#define GetPublicKey_size                        109
#define PublicKey_size                           (121 + HDNodeType_size)
#define GetAddress_size                          (2250 + 15*HDNodeType_size + 15*HDNodeType_size)
#define Address_size                             133
#define SignMessage_size                         1100
#define MessageSignature_size                    200
#define VerifyMessage_size                       1250
#define SignTx_size                              73
#define TxRequest_size                           2191
#define TxRequestDetailsType_size                52
#define TxRequestSerializedType_size             2132
#define TxAck_size                               (8131 + 1*15*HDNodeType_size + 1*15*HDNodeType_size + 1*15*HDNodeType_size + 1*15*HDNodeType_size)
#define TransactionType_size                     (8125 + 1*15*HDNodeType_size + 1*15*HDNodeType_size + 1*15*HDNodeType_size + 1*15*HDNodeType_size)
#define TxInputType_size                         (3987 + 15*HDNodeType_size + 15*HDNodeType_size)
#define TxOutputBinType_size                     540
#define TxOutputType_size                        (2497 + 15*HDNodeType_size + 15*HDNodeType_size)

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MESSAGES_BITCOIN_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
