/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 */

#include "messages.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



typedef struct {
    bool wire_in;
} wire_in_struct;

static const pb_field_t wire_in_field = 
      PB_FIELD(50002, BOOL    , OPTEXT, STATIC  , FIRST, wire_in_struct, wire_in, wire_in, 0);

const pb_extension_type_t wire_in = {
    NULL,
    NULL,
    &wire_in_field
};

typedef struct {
    bool wire_out;
} wire_out_struct;

static const pb_field_t wire_out_field = 
      PB_FIELD(50003, BOOL    , OPTEXT, STATIC  , FIRST, wire_out_struct, wire_out, wire_out, 0);

const pb_extension_type_t wire_out = {
    NULL,
    NULL,
    &wire_out_field
};

typedef struct {
    bool wire_debug_in;
} wire_debug_in_struct;

static const pb_field_t wire_debug_in_field = 
      PB_FIELD(50004, BOOL    , OPTEXT, STATIC  , FIRST, wire_debug_in_struct, wire_debug_in, wire_debug_in, 0);

const pb_extension_type_t wire_debug_in = {
    NULL,
    NULL,
    &wire_debug_in_field
};

typedef struct {
    bool wire_debug_out;
} wire_debug_out_struct;

static const pb_field_t wire_debug_out_field = 
      PB_FIELD(50005, BOOL    , OPTEXT, STATIC  , FIRST, wire_debug_out_struct, wire_debug_out, wire_debug_out, 0);

const pb_extension_type_t wire_debug_out = {
    NULL,
    NULL,
    &wire_debug_out_field
};

typedef struct {
    bool wire_tiny;
} wire_tiny_struct;

static const pb_field_t wire_tiny_field = 
      PB_FIELD(50006, BOOL    , OPTEXT, STATIC  , FIRST, wire_tiny_struct, wire_tiny, wire_tiny, 0);

const pb_extension_type_t wire_tiny = {
    NULL,
    NULL,
    &wire_tiny_field
};

typedef struct {
    bool wire_bootloader;
} wire_bootloader_struct;

static const pb_field_t wire_bootloader_field = 
      PB_FIELD(50007, BOOL    , OPTEXT, STATIC  , FIRST, wire_bootloader_struct, wire_bootloader, wire_bootloader, 0);

const pb_extension_type_t wire_bootloader = {
    NULL,
    NULL,
    &wire_bootloader_field
};

typedef struct {
    bool wire_no_fsm;
} wire_no_fsm_struct;

static const pb_field_t wire_no_fsm_field = 
      PB_FIELD(50008, BOOL    , OPTEXT, STATIC  , FIRST, wire_no_fsm_struct, wire_no_fsm, wire_no_fsm, 0);

const pb_extension_type_t wire_no_fsm = {
    NULL,
    NULL,
    &wire_no_fsm_field
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for wire_no_fsm_struct.wire_no_fsm is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
