/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 */

#include "messages-ethereum.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t EthereumGetPublicKey_fields[3] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, EthereumGetPublicKey, address_n, address_n, 0),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, EthereumGetPublicKey, show_display, address_n, 0),
    PB_LAST_FIELD
};

const pb_field_t EthereumPublicKey_fields[3] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, EthereumPublicKey, node, node, &HDNodeType_fields),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, EthereumPublicKey, xpub, node, 0),
    PB_LAST_FIELD
};

const pb_field_t EthereumGetAddress_fields[3] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, EthereumGetAddress, address_n, address_n, 0),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, EthereumGetAddress, show_display, address_n, 0),
    PB_LAST_FIELD
};

const pb_field_t EthereumAddress_fields[3] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, CALLBACK, FIRST, EthereumAddress, old_address, old_address, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, EthereumAddress, address, old_address, 0),
    PB_LAST_FIELD
};

const pb_field_t EthereumSignTx_fields[11] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, EthereumSignTx, address_n, address_n, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, STATIC  , OTHER, EthereumSignTx, nonce, address_n, 0),
    PB_FIELD(  3, BYTES   , OPTIONAL, STATIC  , OTHER, EthereumSignTx, gas_price, nonce, 0),
    PB_FIELD(  4, BYTES   , OPTIONAL, STATIC  , OTHER, EthereumSignTx, gas_limit, gas_price, 0),
    PB_FIELD(  6, BYTES   , OPTIONAL, STATIC  , OTHER, EthereumSignTx, value, gas_limit, 0),
    PB_FIELD(  7, BYTES   , OPTIONAL, STATIC  , OTHER, EthereumSignTx, data_initial_chunk, value, 0),
    PB_FIELD(  8, UINT32  , OPTIONAL, STATIC  , OTHER, EthereumSignTx, data_length, data_initial_chunk, 0),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC  , OTHER, EthereumSignTx, chain_id, data_length, 0),
    PB_FIELD( 10, UINT32  , OPTIONAL, STATIC  , OTHER, EthereumSignTx, tx_type, chain_id, 0),
    PB_FIELD( 11, STRING  , OPTIONAL, STATIC  , OTHER, EthereumSignTx, to, tx_type, 0),
    PB_LAST_FIELD
};

const pb_field_t EthereumTxRequest_fields[5] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, EthereumTxRequest, data_length, data_length, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, EthereumTxRequest, signature_v, data_length, 0),
    PB_FIELD(  3, BYTES   , OPTIONAL, STATIC  , OTHER, EthereumTxRequest, signature_r, signature_v, 0),
    PB_FIELD(  4, BYTES   , OPTIONAL, STATIC  , OTHER, EthereumTxRequest, signature_s, signature_r, 0),
    PB_LAST_FIELD
};

const pb_field_t EthereumTxAck_fields[2] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, STATIC  , FIRST, EthereumTxAck, data_chunk, data_chunk, 0),
    PB_LAST_FIELD
};

const pb_field_t EthereumSignMessage_fields[3] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, EthereumSignMessage, address_n, address_n, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, STATIC  , OTHER, EthereumSignMessage, message, address_n, 0),
    PB_LAST_FIELD
};

const pb_field_t EthereumMessageSignature_fields[3] = {
    PB_FIELD(  2, BYTES   , OPTIONAL, STATIC  , FIRST, EthereumMessageSignature, signature, signature, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, EthereumMessageSignature, address, signature, 0),
    PB_LAST_FIELD
};

const pb_field_t EthereumVerifyMessage_fields[4] = {
    PB_FIELD(  2, BYTES   , OPTIONAL, STATIC  , FIRST, EthereumVerifyMessage, signature, signature, 0),
    PB_FIELD(  3, BYTES   , OPTIONAL, STATIC  , OTHER, EthereumVerifyMessage, message, signature, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, STATIC  , OTHER, EthereumVerifyMessage, address, message, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(EthereumPublicKey, node) < 65536 && pb_membersize(EthereumSignTx, data_initial_chunk) < 65536 && pb_membersize(EthereumTxAck, data_chunk) < 65536 && pb_membersize(EthereumSignMessage, message) < 65536 && pb_membersize(EthereumVerifyMessage, message) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_EthereumGetPublicKey_EthereumPublicKey_EthereumGetAddress_EthereumAddress_EthereumSignTx_EthereumTxRequest_EthereumTxAck_EthereumSignMessage_EthereumMessageSignature_EthereumVerifyMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for EthereumVerifyMessage.message is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
