/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 */

#include "messages-management.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const char LoadDevice_language_default[17] = "english";
const uint32_t ResetDevice_strength_default = 256u;
const char ResetDevice_language_default[17] = "english";
const char RecoveryDevice_language_default[17] = "english";


const pb_field_t Initialize_fields[3] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, STATIC  , FIRST, Initialize, state, state, 0),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, Initialize, skip_passphrase, state, 0),
    PB_LAST_FIELD
};

const pb_field_t GetFeatures_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t Features_fields[28] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, Features, vendor, vendor, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, Features, major_version, vendor, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, Features, minor_version, major_version, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, Features, patch_version, minor_version, 0),
    PB_FIELD(  5, BOOL    , OPTIONAL, STATIC  , OTHER, Features, bootloader_mode, patch_version, 0),
    PB_FIELD(  6, STRING  , OPTIONAL, STATIC  , OTHER, Features, device_id, bootloader_mode, 0),
    PB_FIELD(  7, BOOL    , OPTIONAL, STATIC  , OTHER, Features, pin_protection, device_id, 0),
    PB_FIELD(  8, BOOL    , OPTIONAL, STATIC  , OTHER, Features, passphrase_protection, pin_protection, 0),
    PB_FIELD(  9, STRING  , OPTIONAL, STATIC  , OTHER, Features, language, passphrase_protection, 0),
    PB_FIELD( 10, STRING  , OPTIONAL, STATIC  , OTHER, Features, label, language, 0),
    PB_FIELD( 12, BOOL    , OPTIONAL, STATIC  , OTHER, Features, initialized, label, 0),
    PB_FIELD( 13, BYTES   , OPTIONAL, STATIC  , OTHER, Features, revision, initialized, 0),
    PB_FIELD( 14, BYTES   , OPTIONAL, STATIC  , OTHER, Features, bootloader_hash, revision, 0),
    PB_FIELD( 15, BOOL    , OPTIONAL, STATIC  , OTHER, Features, imported, bootloader_hash, 0),
    PB_FIELD( 16, BOOL    , OPTIONAL, STATIC  , OTHER, Features, pin_cached, imported, 0),
    PB_FIELD( 17, BOOL    , OPTIONAL, STATIC  , OTHER, Features, passphrase_cached, pin_cached, 0),
    PB_FIELD( 18, BOOL    , OPTIONAL, STATIC  , OTHER, Features, firmware_present, passphrase_cached, 0),
    PB_FIELD( 19, BOOL    , OPTIONAL, STATIC  , OTHER, Features, needs_backup, firmware_present, 0),
    PB_FIELD( 20, UINT32  , OPTIONAL, STATIC  , OTHER, Features, flags, needs_backup, 0),
    PB_FIELD( 21, STRING  , OPTIONAL, STATIC  , OTHER, Features, model, flags, 0),
    PB_FIELD( 22, UINT32  , OPTIONAL, STATIC  , OTHER, Features, fw_major, model, 0),
    PB_FIELD( 23, UINT32  , OPTIONAL, STATIC  , OTHER, Features, fw_minor, fw_major, 0),
    PB_FIELD( 24, UINT32  , OPTIONAL, STATIC  , OTHER, Features, fw_patch, fw_minor, 0),
    PB_FIELD( 25, STRING  , OPTIONAL, STATIC  , OTHER, Features, fw_vendor, fw_patch, 0),
    PB_FIELD( 26, BYTES   , OPTIONAL, STATIC  , OTHER, Features, fw_vendor_keys, fw_vendor, 0),
    PB_FIELD( 27, BOOL    , OPTIONAL, STATIC  , OTHER, Features, unfinished_backup, fw_vendor_keys, 0),
    PB_FIELD( 28, BOOL    , OPTIONAL, STATIC  , OTHER, Features, no_backup, unfinished_backup, 0),
    PB_LAST_FIELD
};

const pb_field_t ClearSession_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t ApplySettings_fields[8] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, ApplySettings, language, language, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, ApplySettings, label, language, 0),
    PB_FIELD(  3, BOOL    , OPTIONAL, STATIC  , OTHER, ApplySettings, use_passphrase, label, 0),
    PB_FIELD(  4, BYTES   , OPTIONAL, STATIC  , OTHER, ApplySettings, homescreen, use_passphrase, 0),
    PB_FIELD(  5, UENUM   , OPTIONAL, STATIC  , OTHER, ApplySettings, passphrase_source, homescreen, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, ApplySettings, auto_lock_delay_ms, passphrase_source, 0),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC  , OTHER, ApplySettings, display_rotation, auto_lock_delay_ms, 0),
    PB_LAST_FIELD
};

const pb_field_t ApplyFlags_fields[2] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, ApplyFlags, flags, flags, 0),
    PB_LAST_FIELD
};

const pb_field_t ChangePin_fields[2] = {
    PB_FIELD(  1, BOOL    , OPTIONAL, STATIC  , FIRST, ChangePin, remove, remove, 0),
    PB_LAST_FIELD
};

const pb_field_t Ping_fields[5] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, Ping, message, message, 0),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, Ping, button_protection, message, 0),
    PB_FIELD(  3, BOOL    , OPTIONAL, STATIC  , OTHER, Ping, pin_protection, button_protection, 0),
    PB_FIELD(  4, BOOL    , OPTIONAL, STATIC  , OTHER, Ping, passphrase_protection, pin_protection, 0),
    PB_LAST_FIELD
};

const pb_field_t Cancel_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t GetEntropy_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, GetEntropy, size, size, 0),
    PB_LAST_FIELD
};

const pb_field_t Entropy_fields[2] = {
    PB_FIELD(  1, BYTES   , REQUIRED, STATIC  , FIRST, Entropy, entropy, entropy, 0),
    PB_LAST_FIELD
};

const pb_field_t WipeDevice_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t LoadDevice_fields[9] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, LoadDevice, mnemonic, mnemonic, 0),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, LoadDevice, node, mnemonic, &HDNodeType_fields),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, LoadDevice, pin, node, 0),
    PB_FIELD(  4, BOOL    , OPTIONAL, STATIC  , OTHER, LoadDevice, passphrase_protection, pin, 0),
    PB_FIELD(  5, STRING  , OPTIONAL, STATIC  , OTHER, LoadDevice, language, passphrase_protection, &LoadDevice_language_default),
    PB_FIELD(  6, STRING  , OPTIONAL, STATIC  , OTHER, LoadDevice, label, language, 0),
    PB_FIELD(  7, BOOL    , OPTIONAL, STATIC  , OTHER, LoadDevice, skip_checksum, label, 0),
    PB_FIELD(  8, UINT32  , OPTIONAL, STATIC  , OTHER, LoadDevice, u2f_counter, skip_checksum, 0),
    PB_LAST_FIELD
};

const pb_field_t ResetDevice_fields[10] = {
    PB_FIELD(  1, BOOL    , OPTIONAL, STATIC  , FIRST, ResetDevice, display_random, display_random, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, ResetDevice, strength, display_random, &ResetDevice_strength_default),
    PB_FIELD(  3, BOOL    , OPTIONAL, STATIC  , OTHER, ResetDevice, passphrase_protection, strength, 0),
    PB_FIELD(  4, BOOL    , OPTIONAL, STATIC  , OTHER, ResetDevice, pin_protection, passphrase_protection, 0),
    PB_FIELD(  5, STRING  , OPTIONAL, STATIC  , OTHER, ResetDevice, language, pin_protection, &ResetDevice_language_default),
    PB_FIELD(  6, STRING  , OPTIONAL, STATIC  , OTHER, ResetDevice, label, language, 0),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC  , OTHER, ResetDevice, u2f_counter, label, 0),
    PB_FIELD(  8, BOOL    , OPTIONAL, STATIC  , OTHER, ResetDevice, skip_backup, u2f_counter, 0),
    PB_FIELD(  9, BOOL    , OPTIONAL, STATIC  , OTHER, ResetDevice, no_backup, skip_backup, 0),
    PB_LAST_FIELD
};

const pb_field_t BackupDevice_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t EntropyRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t EntropyAck_fields[2] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, STATIC  , FIRST, EntropyAck, entropy, entropy, 0),
    PB_LAST_FIELD
};

const pb_field_t RecoveryDevice_fields[10] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, RecoveryDevice, word_count, word_count, 0),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, RecoveryDevice, passphrase_protection, word_count, 0),
    PB_FIELD(  3, BOOL    , OPTIONAL, STATIC  , OTHER, RecoveryDevice, pin_protection, passphrase_protection, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, STATIC  , OTHER, RecoveryDevice, language, pin_protection, &RecoveryDevice_language_default),
    PB_FIELD(  5, STRING  , OPTIONAL, STATIC  , OTHER, RecoveryDevice, label, language, 0),
    PB_FIELD(  6, BOOL    , OPTIONAL, STATIC  , OTHER, RecoveryDevice, enforce_wordlist, label, 0),
    PB_FIELD(  8, UENUM   , OPTIONAL, STATIC  , OTHER, RecoveryDevice, type, enforce_wordlist, 0),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC  , OTHER, RecoveryDevice, u2f_counter, type, 0),
    PB_FIELD( 10, BOOL    , OPTIONAL, STATIC  , OTHER, RecoveryDevice, dry_run, u2f_counter, 0),
    PB_LAST_FIELD
};

const pb_field_t WordRequest_fields[2] = {
    PB_FIELD(  1, UENUM   , OPTIONAL, STATIC  , FIRST, WordRequest, type, type, 0),
    PB_LAST_FIELD
};

const pb_field_t WordAck_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, WordAck, word, word, 0),
    PB_LAST_FIELD
};

const pb_field_t SetU2FCounter_fields[2] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, SetU2FCounter, u2f_counter, u2f_counter, 0),
    PB_LAST_FIELD
};





/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ApplySettings, homescreen) < 65536 && pb_membersize(Entropy, entropy) < 65536 && pb_membersize(LoadDevice, node) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Initialize_GetFeatures_Features_ClearSession_ApplySettings_ApplyFlags_ChangePin_Ping_Cancel_GetEntropy_Entropy_WipeDevice_LoadDevice_ResetDevice_BackupDevice_EntropyRequest_EntropyAck_RecoveryDevice_WordRequest_WordAck_SetU2FCounter)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for Entropy.entropy is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
