/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 */

#include "messages-bitcoin.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const char GetPublicKey_coin_name_default[21] = "Bitcoin";
const InputScriptType GetPublicKey_script_type_default = InputScriptType_SPENDADDRESS;
const char GetAddress_coin_name_default[21] = "Bitcoin";
const InputScriptType GetAddress_script_type_default = InputScriptType_SPENDADDRESS;
const char SignMessage_coin_name_default[21] = "Bitcoin";
const InputScriptType SignMessage_script_type_default = InputScriptType_SPENDADDRESS;
const char VerifyMessage_coin_name_default[21] = "Bitcoin";
const char SignTx_coin_name_default[21] = "Bitcoin";
const uint32_t SignTx_version_default = 1u;
const uint32_t SignTx_lock_time_default = 0u;
const uint32_t TxInputType_sequence_default = 4294967295u;
const InputScriptType TxInputType_script_type_default = InputScriptType_SPENDADDRESS;


const pb_field_t MultisigRedeemScriptType_fields[6] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, MultisigRedeemScriptType, pubkeys, pubkeys, &HDNodePathType_fields),
    PB_FIELD(  2, BYTES   , REPEATED, STATIC  , OTHER, MultisigRedeemScriptType, signatures, pubkeys, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, MultisigRedeemScriptType, m, signatures, 0),
    PB_FIELD(  4, MESSAGE , REPEATED, STATIC  , OTHER, MultisigRedeemScriptType, nodes, m, &HDNodeType_fields),
    PB_FIELD(  5, UINT32  , REPEATED, STATIC  , OTHER, MultisigRedeemScriptType, address_n, nodes, 0),
    PB_LAST_FIELD
};

const pb_field_t HDNodePathType_fields[3] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, HDNodePathType, node, node, &HDNodeType_fields),
    PB_FIELD(  2, UINT32  , REPEATED, STATIC  , OTHER, HDNodePathType, address_n, node, 0),
    PB_LAST_FIELD
};

const pb_field_t GetPublicKey_fields[6] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, GetPublicKey, address_n, address_n, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, GetPublicKey, ecdsa_curve_name, address_n, 0),
    PB_FIELD(  3, BOOL    , OPTIONAL, STATIC  , OTHER, GetPublicKey, show_display, ecdsa_curve_name, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, STATIC  , OTHER, GetPublicKey, coin_name, show_display, &GetPublicKey_coin_name_default),
    PB_FIELD(  5, UENUM   , OPTIONAL, STATIC  , OTHER, GetPublicKey, script_type, coin_name, &GetPublicKey_script_type_default),
    PB_LAST_FIELD
};

const pb_field_t PublicKey_fields[3] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, PublicKey, node, node, &HDNodeType_fields),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, PublicKey, xpub, node, 0),
    PB_LAST_FIELD
};

const pb_field_t GetAddress_fields[6] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, GetAddress, address_n, address_n, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, GetAddress, coin_name, address_n, &GetAddress_coin_name_default),
    PB_FIELD(  3, BOOL    , OPTIONAL, STATIC  , OTHER, GetAddress, show_display, coin_name, 0),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, GetAddress, multisig, show_display, &MultisigRedeemScriptType_fields),
    PB_FIELD(  5, UENUM   , OPTIONAL, STATIC  , OTHER, GetAddress, script_type, multisig, &GetAddress_script_type_default),
    PB_LAST_FIELD
};

const pb_field_t Address_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, Address, address, address, 0),
    PB_LAST_FIELD
};

const pb_field_t SignMessage_fields[5] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, SignMessage, address_n, address_n, 0),
    PB_FIELD(  2, BYTES   , REQUIRED, STATIC  , OTHER, SignMessage, message, address_n, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, SignMessage, coin_name, message, &SignMessage_coin_name_default),
    PB_FIELD(  4, UENUM   , OPTIONAL, STATIC  , OTHER, SignMessage, script_type, coin_name, &SignMessage_script_type_default),
    PB_LAST_FIELD
};

const pb_field_t MessageSignature_fields[3] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, MessageSignature, address, address, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, STATIC  , OTHER, MessageSignature, signature, address, 0),
    PB_LAST_FIELD
};

const pb_field_t VerifyMessage_fields[5] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, VerifyMessage, address, address, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, STATIC  , OTHER, VerifyMessage, signature, address, 0),
    PB_FIELD(  3, BYTES   , OPTIONAL, STATIC  , OTHER, VerifyMessage, message, signature, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, STATIC  , OTHER, VerifyMessage, coin_name, message, &VerifyMessage_coin_name_default),
    PB_LAST_FIELD
};

const pb_field_t SignTx_fields[11] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, SignTx, outputs_count, outputs_count, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, SignTx, inputs_count, outputs_count, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, SignTx, coin_name, inputs_count, &SignTx_coin_name_default),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, SignTx, version, coin_name, &SignTx_version_default),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, SignTx, lock_time, version, &SignTx_lock_time_default),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, SignTx, expiry, lock_time, 0),
    PB_FIELD(  7, BOOL    , OPTIONAL, STATIC  , OTHER, SignTx, overwintered, expiry, 0),
    PB_FIELD(  8, UINT32  , OPTIONAL, STATIC  , OTHER, SignTx, version_group_id, overwintered, 0),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC  , OTHER, SignTx, timestamp, version_group_id, 0),
    PB_FIELD( 10, UINT32  , OPTIONAL, STATIC  , OTHER, SignTx, branch_id, timestamp, 0),
    PB_LAST_FIELD
};

const pb_field_t TxRequest_fields[4] = {
    PB_FIELD(  1, UENUM   , OPTIONAL, STATIC  , FIRST, TxRequest, request_type, request_type, 0),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, TxRequest, details, request_type, &TxRequestDetailsType_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, TxRequest, serialized, details, &TxRequestSerializedType_fields),
    PB_LAST_FIELD
};

const pb_field_t TxRequestDetailsType_fields[5] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, TxRequestDetailsType, request_index, request_index, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, STATIC  , OTHER, TxRequestDetailsType, tx_hash, request_index, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, TxRequestDetailsType, extra_data_len, tx_hash, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, TxRequestDetailsType, extra_data_offset, extra_data_len, 0),
    PB_LAST_FIELD
};

const pb_field_t TxRequestSerializedType_fields[4] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, TxRequestSerializedType, signature_index, signature_index, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, STATIC  , OTHER, TxRequestSerializedType, signature, signature_index, 0),
    PB_FIELD(  3, BYTES   , OPTIONAL, STATIC  , OTHER, TxRequestSerializedType, serialized_tx, signature, 0),
    PB_LAST_FIELD
};

const pb_field_t TxAck_fields[2] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, TxAck, tx, tx, &TransactionType_fields),
    PB_LAST_FIELD
};

const pb_field_t TransactionType_fields[15] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, TransactionType, version, version, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, STATIC  , OTHER, TransactionType, inputs, version, &TxInputType_fields),
    PB_FIELD(  3, MESSAGE , REPEATED, STATIC  , OTHER, TransactionType, bin_outputs, inputs, &TxOutputBinType_fields),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, TransactionType, lock_time, bin_outputs, 0),
    PB_FIELD(  5, MESSAGE , REPEATED, STATIC  , OTHER, TransactionType, outputs, lock_time, &TxOutputType_fields),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, TransactionType, inputs_cnt, outputs, 0),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC  , OTHER, TransactionType, outputs_cnt, inputs_cnt, 0),
    PB_FIELD(  8, BYTES   , OPTIONAL, STATIC  , OTHER, TransactionType, extra_data, outputs_cnt, 0),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC  , OTHER, TransactionType, extra_data_len, extra_data, 0),
    PB_FIELD( 10, UINT32  , OPTIONAL, STATIC  , OTHER, TransactionType, expiry, extra_data_len, 0),
    PB_FIELD( 11, BOOL    , OPTIONAL, STATIC  , OTHER, TransactionType, overwintered, expiry, 0),
    PB_FIELD( 12, UINT32  , OPTIONAL, STATIC  , OTHER, TransactionType, version_group_id, overwintered, 0),
    PB_FIELD( 13, UINT32  , OPTIONAL, STATIC  , OTHER, TransactionType, timestamp, version_group_id, 0),
    PB_FIELD( 14, UINT32  , OPTIONAL, STATIC  , OTHER, TransactionType, branch_id, timestamp, 0),
    PB_LAST_FIELD
};

const pb_field_t TxInputType_fields[13] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, TxInputType, address_n, address_n, 0),
    PB_FIELD(  2, BYTES   , REQUIRED, STATIC  , OTHER, TxInputType, prev_hash, address_n, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, TxInputType, prev_index, prev_hash, 0),
    PB_FIELD(  4, BYTES   , OPTIONAL, STATIC  , OTHER, TxInputType, script_sig, prev_index, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, TxInputType, sequence, script_sig, &TxInputType_sequence_default),
    PB_FIELD(  6, UENUM   , OPTIONAL, STATIC  , OTHER, TxInputType, script_type, sequence, &TxInputType_script_type_default),
    PB_FIELD(  7, MESSAGE , OPTIONAL, STATIC  , OTHER, TxInputType, multisig, script_type, &MultisigRedeemScriptType_fields),
    PB_FIELD(  8, UINT64  , OPTIONAL, STATIC  , OTHER, TxInputType, amount, multisig, 0),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC  , OTHER, TxInputType, decred_tree, amount, 0),
    PB_FIELD( 10, UINT32  , OPTIONAL, STATIC  , OTHER, TxInputType, decred_script_version, decred_tree, 0),
    PB_FIELD( 11, BYTES   , OPTIONAL, STATIC  , OTHER, TxInputType, prev_block_hash_bip115, decred_script_version, 0),
    PB_FIELD( 12, UINT32  , OPTIONAL, STATIC  , OTHER, TxInputType, prev_block_height_bip115, prev_block_hash_bip115, 0),
    PB_LAST_FIELD
};

const pb_field_t TxOutputBinType_fields[4] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, TxOutputBinType, amount, amount, 0),
    PB_FIELD(  2, BYTES   , REQUIRED, STATIC  , OTHER, TxOutputBinType, script_pubkey, amount, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, TxOutputBinType, decred_script_version, script_pubkey, 0),
    PB_LAST_FIELD
};

const pb_field_t TxOutputType_fields[10] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, TxOutputType, address, address, 0),
    PB_FIELD(  2, UINT32  , REPEATED, STATIC  , OTHER, TxOutputType, address_n, address, 0),
    PB_FIELD(  3, UINT64  , REQUIRED, STATIC  , OTHER, TxOutputType, amount, address_n, 0),
    PB_FIELD(  4, UENUM   , REQUIRED, STATIC  , OTHER, TxOutputType, script_type, amount, 0),
    PB_FIELD(  5, MESSAGE , OPTIONAL, STATIC  , OTHER, TxOutputType, multisig, script_type, &MultisigRedeemScriptType_fields),
    PB_FIELD(  6, BYTES   , OPTIONAL, STATIC  , OTHER, TxOutputType, op_return_data, multisig, 0),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC  , OTHER, TxOutputType, decred_script_version, op_return_data, 0),
    PB_FIELD(  8, BYTES   , OPTIONAL, STATIC  , OTHER, TxOutputType, block_hash_bip115, decred_script_version, 0),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC  , OTHER, TxOutputType, block_height_bip115, block_hash_bip115, 0),
    PB_LAST_FIELD
};





/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MultisigRedeemScriptType, pubkeys[0]) < 65536 && pb_membersize(MultisigRedeemScriptType, nodes[0]) < 65536 && pb_membersize(HDNodePathType, node) < 65536 && pb_membersize(PublicKey, node) < 65536 && pb_membersize(GetAddress, multisig) < 65536 && pb_membersize(SignMessage, message) < 65536 && pb_membersize(VerifyMessage, message) < 65536 && pb_membersize(TxRequest, details) < 65536 && pb_membersize(TxRequest, serialized) < 65536 && pb_membersize(TxRequestSerializedType, serialized_tx) < 65536 && pb_membersize(TxAck, tx) < 65536 && pb_membersize(TransactionType, inputs[0]) < 65536 && pb_membersize(TransactionType, bin_outputs[0]) < 65536 && pb_membersize(TransactionType, outputs[0]) < 65536 && pb_membersize(TransactionType, extra_data) < 65536 && pb_membersize(TxInputType, script_sig) < 65536 && pb_membersize(TxInputType, multisig) < 65536 && pb_membersize(TxOutputBinType, script_pubkey) < 65536 && pb_membersize(TxOutputType, multisig) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_MultisigRedeemScriptType_HDNodePathType_GetPublicKey_PublicKey_GetAddress_Address_SignMessage_MessageSignature_VerifyMessage_SignTx_TxRequest_TxRequestDetailsType_TxRequestSerializedType_TxAck_TransactionType_TxInputType_TxOutputBinType_TxOutputType)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for TxRequestSerializedType.serialized_tx is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
