/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 */

#include "messages-stellar.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t StellarAssetType_fields[4] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, StellarAssetType, type, type, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, StellarAssetType, code, type, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, StellarAssetType, issuer, code, 0),
    PB_LAST_FIELD
};

const pb_field_t StellarGetAddress_fields[3] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, StellarGetAddress, address_n, address_n, 0),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, StellarGetAddress, show_display, address_n, 0),
    PB_LAST_FIELD
};

const pb_field_t StellarAddress_fields[2] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, StellarAddress, address, address, 0),
    PB_LAST_FIELD
};

const pb_field_t StellarSignTx_fields[13] = {
    PB_FIELD(  2, UINT32  , REPEATED, STATIC  , FIRST, StellarSignTx, address_n, address_n, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, StellarSignTx, network_passphrase, address_n, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, STATIC  , OTHER, StellarSignTx, source_account, network_passphrase, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, StellarSignTx, fee, source_account, 0),
    PB_FIELD(  6, UINT64  , OPTIONAL, STATIC  , OTHER, StellarSignTx, sequence_number, fee, 0),
    PB_FIELD(  8, UINT32  , OPTIONAL, STATIC  , OTHER, StellarSignTx, timebounds_start, sequence_number, 0),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC  , OTHER, StellarSignTx, timebounds_end, timebounds_start, 0),
    PB_FIELD( 10, UINT32  , OPTIONAL, STATIC  , OTHER, StellarSignTx, memo_type, timebounds_end, 0),
    PB_FIELD( 11, STRING  , OPTIONAL, STATIC  , OTHER, StellarSignTx, memo_text, memo_type, 0),
    PB_FIELD( 12, UINT64  , OPTIONAL, STATIC  , OTHER, StellarSignTx, memo_id, memo_text, 0),
    PB_FIELD( 13, BYTES   , OPTIONAL, STATIC  , OTHER, StellarSignTx, memo_hash, memo_id, 0),
    PB_FIELD( 14, UINT32  , OPTIONAL, STATIC  , OTHER, StellarSignTx, num_operations, memo_hash, 0),
    PB_LAST_FIELD
};

const pb_field_t StellarTxOpRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t StellarPaymentOp_fields[5] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, StellarPaymentOp, source_account, source_account, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, StellarPaymentOp, destination_account, source_account, 0),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, StellarPaymentOp, asset, destination_account, &StellarAssetType_fields),
    PB_FIELD(  4, SINT64  , OPTIONAL, STATIC  , OTHER, StellarPaymentOp, amount, asset, 0),
    PB_LAST_FIELD
};

const pb_field_t StellarCreateAccountOp_fields[4] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, StellarCreateAccountOp, source_account, source_account, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, StellarCreateAccountOp, new_account, source_account, 0),
    PB_FIELD(  3, SINT64  , OPTIONAL, STATIC  , OTHER, StellarCreateAccountOp, starting_balance, new_account, 0),
    PB_LAST_FIELD
};

const pb_field_t StellarPathPaymentOp_fields[8] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, StellarPathPaymentOp, source_account, source_account, 0),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, StellarPathPaymentOp, send_asset, source_account, &StellarAssetType_fields),
    PB_FIELD(  3, SINT64  , OPTIONAL, STATIC  , OTHER, StellarPathPaymentOp, send_max, send_asset, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, STATIC  , OTHER, StellarPathPaymentOp, destination_account, send_max, 0),
    PB_FIELD(  5, MESSAGE , OPTIONAL, STATIC  , OTHER, StellarPathPaymentOp, destination_asset, destination_account, &StellarAssetType_fields),
    PB_FIELD(  6, SINT64  , OPTIONAL, STATIC  , OTHER, StellarPathPaymentOp, destination_amount, destination_asset, 0),
    PB_FIELD(  7, MESSAGE , REPEATED, STATIC  , OTHER, StellarPathPaymentOp, paths, destination_amount, &StellarAssetType_fields),
    PB_LAST_FIELD
};

const pb_field_t StellarManageOfferOp_fields[8] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, StellarManageOfferOp, source_account, source_account, 0),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, StellarManageOfferOp, selling_asset, source_account, &StellarAssetType_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, StellarManageOfferOp, buying_asset, selling_asset, &StellarAssetType_fields),
    PB_FIELD(  4, SINT64  , OPTIONAL, STATIC  , OTHER, StellarManageOfferOp, amount, buying_asset, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, StellarManageOfferOp, price_n, amount, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, StellarManageOfferOp, price_d, price_n, 0),
    PB_FIELD(  7, UINT64  , OPTIONAL, STATIC  , OTHER, StellarManageOfferOp, offer_id, price_d, 0),
    PB_LAST_FIELD
};

const pb_field_t StellarCreatePassiveOfferOp_fields[7] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, StellarCreatePassiveOfferOp, source_account, source_account, 0),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, StellarCreatePassiveOfferOp, selling_asset, source_account, &StellarAssetType_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, StellarCreatePassiveOfferOp, buying_asset, selling_asset, &StellarAssetType_fields),
    PB_FIELD(  4, SINT64  , OPTIONAL, STATIC  , OTHER, StellarCreatePassiveOfferOp, amount, buying_asset, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, StellarCreatePassiveOfferOp, price_n, amount, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, StellarCreatePassiveOfferOp, price_d, price_n, 0),
    PB_LAST_FIELD
};

const pb_field_t StellarSetOptionsOp_fields[13] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, StellarSetOptionsOp, source_account, source_account, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, StellarSetOptionsOp, inflation_destination_account, source_account, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, StellarSetOptionsOp, clear_flags, inflation_destination_account, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, StellarSetOptionsOp, set_flags, clear_flags, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, StellarSetOptionsOp, master_weight, set_flags, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, StellarSetOptionsOp, low_threshold, master_weight, 0),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC  , OTHER, StellarSetOptionsOp, medium_threshold, low_threshold, 0),
    PB_FIELD(  8, UINT32  , OPTIONAL, STATIC  , OTHER, StellarSetOptionsOp, high_threshold, medium_threshold, 0),
    PB_FIELD(  9, STRING  , OPTIONAL, STATIC  , OTHER, StellarSetOptionsOp, home_domain, high_threshold, 0),
    PB_FIELD( 10, UINT32  , OPTIONAL, STATIC  , OTHER, StellarSetOptionsOp, signer_type, home_domain, 0),
    PB_FIELD( 11, BYTES   , OPTIONAL, STATIC  , OTHER, StellarSetOptionsOp, signer_key, signer_type, 0),
    PB_FIELD( 12, UINT32  , OPTIONAL, STATIC  , OTHER, StellarSetOptionsOp, signer_weight, signer_key, 0),
    PB_LAST_FIELD
};

const pb_field_t StellarChangeTrustOp_fields[4] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, StellarChangeTrustOp, source_account, source_account, 0),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, StellarChangeTrustOp, asset, source_account, &StellarAssetType_fields),
    PB_FIELD(  3, UINT64  , OPTIONAL, STATIC  , OTHER, StellarChangeTrustOp, limit, asset, 0),
    PB_LAST_FIELD
};

const pb_field_t StellarAllowTrustOp_fields[6] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, StellarAllowTrustOp, source_account, source_account, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, StellarAllowTrustOp, trusted_account, source_account, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, StellarAllowTrustOp, asset_type, trusted_account, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, STATIC  , OTHER, StellarAllowTrustOp, asset_code, asset_type, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, StellarAllowTrustOp, is_authorized, asset_code, 0),
    PB_LAST_FIELD
};

const pb_field_t StellarAccountMergeOp_fields[3] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, StellarAccountMergeOp, source_account, source_account, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, StellarAccountMergeOp, destination_account, source_account, 0),
    PB_LAST_FIELD
};

const pb_field_t StellarManageDataOp_fields[4] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, StellarManageDataOp, source_account, source_account, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, StellarManageDataOp, key, source_account, 0),
    PB_FIELD(  3, BYTES   , OPTIONAL, STATIC  , OTHER, StellarManageDataOp, value, key, 0),
    PB_LAST_FIELD
};

const pb_field_t StellarBumpSequenceOp_fields[3] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, StellarBumpSequenceOp, source_account, source_account, 0),
    PB_FIELD(  2, UINT64  , OPTIONAL, STATIC  , OTHER, StellarBumpSequenceOp, bump_to, source_account, 0),
    PB_LAST_FIELD
};

const pb_field_t StellarSignedTx_fields[3] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, STATIC  , FIRST, StellarSignedTx, public_key, public_key, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, STATIC  , OTHER, StellarSignedTx, signature, public_key, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(StellarPaymentOp, asset) < 65536 && pb_membersize(StellarPathPaymentOp, send_asset) < 65536 && pb_membersize(StellarPathPaymentOp, destination_asset) < 65536 && pb_membersize(StellarPathPaymentOp, paths[0]) < 65536 && pb_membersize(StellarManageOfferOp, selling_asset) < 65536 && pb_membersize(StellarManageOfferOp, buying_asset) < 65536 && pb_membersize(StellarCreatePassiveOfferOp, selling_asset) < 65536 && pb_membersize(StellarCreatePassiveOfferOp, buying_asset) < 65536 && pb_membersize(StellarChangeTrustOp, asset) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_StellarAssetType_StellarGetAddress_StellarAddress_StellarSignTx_StellarTxOpRequest_StellarPaymentOp_StellarCreateAccountOp_StellarPathPaymentOp_StellarManageOfferOp_StellarCreatePassiveOfferOp_StellarSetOptionsOp_StellarChangeTrustOp_StellarAllowTrustOp_StellarAccountMergeOp_StellarManageDataOp_StellarBumpSequenceOp_StellarSignedTx)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for StellarSignTx.network_passphrase is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
